import { getDb } from "../db.ts";

const NGINX_CONF_PATH = "/etc/nginx/conf.d/pi-blade.conf";

export async function regenerateNginxConfig() {
  const db = getDb();

  const routes = db.query(`
    SELECT r.id, r.domain, r.project_id
    FROM routes r
    ORDER BY r.domain
  `).all() as any[];

  let config = "# Auto-generated by Pi-Blade — do not edit manually\n\n";

  for (const route of routes) {
    const upstreams = db.query(`
      SELECT u.port, u.weight, b.hostname
      FROM upstreams u
      JOIN blades b ON b.id = u.blade_id
      WHERE u.route_id = ? AND b.status = 'online'
    `).all(route.id) as any[];

    if (upstreams.length === 0) continue;

    const upstreamName = `upstream_${route.domain.replace(/[^a-zA-Z0-9]/g, "_")}`;

    config += `upstream ${upstreamName} {\n`;
    for (const u of upstreams) {
      config += `    server ${u.hostname}:${u.port} weight=${u.weight};\n`;
    }
    config += `}\n\n`;

    config += `server {\n`;
    config += `    listen 80;\n`;
    config += `    server_name ${route.domain};\n\n`;
    config += `    location / {\n`;
    config += `        proxy_pass http://${upstreamName};\n`;
    config += `        proxy_set_header Host $host;\n`;
    config += `        proxy_set_header X-Real-IP $remote_addr;\n`;
    config += `        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n`;
    config += `        proxy_set_header X-Forwarded-Proto $scheme;\n`;
    config += `        proxy_http_version 1.1;\n`;
    config += `        proxy_set_header Upgrade $http_upgrade;\n`;
    config += `        proxy_set_header Connection "upgrade";\n`;
    config += `    }\n`;
    config += `}\n\n`;
  }

  await Bun.write(NGINX_CONF_PATH, config);
  console.log("[nginx] Config regenerated");

  const proc = Bun.spawn(["nginx", "-s", "reload"], { stderr: "pipe" });
  const exitCode = await proc.exited;
  if (exitCode !== 0) {
    const stderr = await new Response(proc.stderr).text();
    console.error(`[nginx] Reload failed: ${stderr}`);
  } else {
    console.log("[nginx] Reloaded");
  }
}
